### ISSUE TITLE
Moving stage

### ISSUE THREAD

**Issue by Medericoder** [TurboWarp/scratch-gui#274] opened 2021-07-15 13:50 UTC
Hi! I found a bug.

When several addons (clones counter, mouse pointer coordinates, gamepad support, debugger) and "30 FPS with interpolation" are activated, the stage move when the mouse pointer move (because of coordinates text).

https://user-images.githubusercontent.com/80577386/125799137-b3c6d5f3-4c92-4cb3-9ede-bf0e7474a944.mp4

**Comment by GarboMuffin** [comment] 2021-07-16 05:57
This is really a Scratch Addons problem, as you've already reported: https://github.com/ScratchAddons/ScratchAddons/issues/3030

Our interpolation label makes it happen more often but it can happen in normal Scratch w/ SA as well

**Comment by GarboMuffin** [comment] 2021-07-16 06:07
Wait, I think the resizing as the mouse moves might be caused by something I changed

**Comment by GarboMuffin** [comment] 2021-07-16 06:11
The resizing stage issue will be fixed in the next addon update (tomorrow-ish for the website, sunday-ish for the desktop app). It will still overflow, though, that's something to address at some point

**Comment by PenguinLover1123** [comment] 2021-08-22 17:32
So make the text be less wide when it's moving the stage. . .

**Comment by GarboMuffin** [comment] 2021-08-22 17:46
The moving stage issue has already been fixed. The stage growing too large issue still exists.

**Comment by GarboMuffin** [comment] 2022-05-29 02:20
This shouldn't be possible anymore. Probably.

If it still happens, comment here and this can be reopened.

**Closed as completed by GarboMuffin** 2022-05-29 02:20 UTC
Labels: upstream
