### ISSUE TITLE
Asking for input directly after hiding monitor doesn’t focus box

### ISSUE THREAD

**Issue by OceanIsEndless** [TurboWarp/scratch-gui#950] opened 2024-08-02 19:39 UTC
low priority-_ish_

Desktop Version: `Electron 29.3.0, Platform darwin arm64, Distribution release-mac-dmg-universal`
This is a weird one, but I encountered it while I was making my project, and I found it to be worth reporting.

Before you yell at me for reporting it in `desktop`, ~this only occurs in the **offline** editor.~

> **Edit:**
> When I first posted this, I couldn’t reproduce the bug in the online editors, but I only tested them in Safari. I should have tried other browsers before assuming that it only occurred in the offline editors (it _does_ occur in the online editors too). But regardless, it’s been fixed now! Yay!… But now after testing it in Chrome, this same bug appears to occur in the _Scratch_ online editor too! Should I report this to them…?

Hiding a monitor and then asking for input directly after (no frames in between) causes the ask box to **not** automatically focus.

![ask bug steps to reproduce](https://github.com/user-attachments/assets/a9e8f3c1-cbfb-4937-8b9d-5dae402bd77c)

As you can see, the ask box is _technically_ focused (expected), but you can't type without clicking into it (unexpected):

<img width="474" alt="ask bug actual behavior" src="https://github.com/user-attachments/assets/859de43d-dcb8-4193-9090-4dff9f11ef58">

[Minimum reproducible example _(change the file extension back to .sb3; GitHub doesn’t support it)_](https://github.com/user-attachments/files/16474194/minimum.reproducible.example.zip)

This bug only seems to occur under very specific circumstances. It does ~_not_~ apparently occur (see my edit) in the [Scratch](https://scratch.mit.edu/projects/editor) & [TurboWarp](https://turbowarp.org/editor) _online_ editors, ~however~ and it _does_ occur in both the [Scratch](https://scratch.mit.edu/download) and [TurboWarp](https://desktop.turbowarp.org/) _offline_ editors. Should I report it to Scratch instead? I’d imagine that TurboWarp Desktop would work much different than the Scratch offline editor does… ~Could it also be something to do with my particular platform _(macOS Sonoma 14.5)_ since it doesn’t occur online, but instead offline~?

It does **not** occur if you do the reverse (show the monitor after hiding it). I’m not really sure what would cause this to work. I found it kind of cool for confirmation messages (where you wouldn’t expect an answer) but this is likely not intended behavior.

**Comment by GarboMuffin** [comment] 2024-08-06 01:30
i'm moving this to scratch-gui because I can reproduce this in Chrome on the online editor

**Closed as completed** 2024-08-06 01:48 UTC
