### ISSUE TITLE
Bug: Changing language with a custom extension will duplicate it

### ISSUE THREAD

**Issue by Mickmick21** [TurboWarp/scratch-gui#593] opened 2022-08-15 18:34 UTC
image:
<img width="293" alt="Capture d’écran 2022-08-15 à 20 33 51" src="https://user-images.githubusercontent.com/110345721/184694733-15a8e773-6ddb-43b8-bf9d-c1b0f9c8a0b7.png">
this is not disturbing (for me)

**Comment by GarboMuffin** [comment] 2022-12-03 19:13
Duplicate of https://github.com/TurboWarp/scratch-gui/issues/593

**Closed as not planned by GarboMuffin** 2022-12-03 19:13 UTC

**Comment by cobaltt7** [comment] 2022-12-03 23:27
This is #593

**Comment by GarboMuffin** [comment] 2022-12-03 23:35
Oops

Duplicate of https://github.com/TurboWarp/scratch-gui/issues/637
