### ISSUE TITLE
Bug - Text areas

### ISSUE THREAD

**Issue by Medericoder** [TurboWarp/scratch-gui#390] opened 2021-12-19 15:25 UTC
Just watch this...

https://user-images.githubusercontent.com/80577386/146680591-ca67bef0-807c-4391-b1bf-4574e6078c29.mp4

**Comment by TheColaber** [comment] 2021-12-20 12:26
Actually, this bug is caused by the devtools addon (which means that this bug also happens with the debugger addon as well), could you create an issue in https://github.com/ScratchAddons/ScratchAddons? Turbowarp pulls its addons from there.

**Comment by GarboMuffin** [comment] 2022-01-22 17:17
This should be fixed in the next update

**Closed as completed by GarboMuffin** 2022-01-22 17:17 UTC
Labels: upstream
